### ISSUE TITLE
Kautionen buchen nicht möglich

### ISSUE THREAD

**Issue by Nitzbon** [BerlusGmbH/Berlussimo#33]
über Mietvertrag/ Kaution buchen: nach Eingabe der Felder Datum und Betrag und Kommentar gibt es folgende Fehlermeldung: Table 'berlussimo.KAUTIONS_BUCHUNGEN' doesn't exist

**Comment by mueller-berlus** [comment]
Dieses Feature wurde schon lange nicht mehr verwendet und funktioniert offenbar auch nicht mehr. Ich bin derzeit dabei eine Auflistung alle Features von Berlussimo zu erstellen, um nicht mehr Aktive zu finden und zu entfernen.
Kautionen werden derzeit unter Kautionen > Kautionsübersicht angezeigt. Hierbei handelt es sich um eine Art Excel Tabelle. Das Feld SOLL dient als Quelle für die Kaution und wird beim erstellen eines Mietvertrages gefüllt. Ich habe die Felddefinitionen in den INSTALL Ordner geschoben und würde Sie bitten diese zu importieren (berlussimo_db_0.4.2.sql). Hinweise zum import fonden Sie in der install_instructions.txt
Bitte entschuldigen Sie die Unannehmlichkeiten.

**Comment by Nitzbon** [comment]
Nach Installation der "berlussimo_db_0.4.2.sql" erscheint die Fehlermeldung: ERROR 1146 (42S02) at line 1: Table 'berlussimo.KAUTION_FELD' doesn't exist. Es sollte vorher noch eine Tabelle erzeugt werden mit den passenden Eigenschaften.

**Comment by mueller-berlus** [comment]
Sie haben völlig Recht. Ich habe die fehlende Definition hinzugefügt.
