### ISSUE TITLE
Generalschlüssel Auswahlfeld nicht vorhanden

### ISSUE THREAD

**Issue by Nitzbon** [BerlusGmbH/Berlussimo#35]
Im Assistent für BK erscheint das Auswahlfeld für den Generalschlüssel nicht.
![generalschlussel bug 04-04-2016](https://cloud.githubusercontent.com/assets/17554642/14264572/37723722-fac0-11e5-9012-8295e35cef24.jpg)

**Comment by mueller-berlus** [comment]
Es fehlen die Einträge in BK_GENERAL_KEYS. Ich habe die Einträge hinzugefügt (berlussimo_db_0.4.3.sql). Ich bitte Sie diese zu importieren (56f68b0).
Vielen Dank für den Hinweis.
