### ISSUE TITLE
Table 'berlussimo.KAUTIONS_BUCHUNGEN' doesn't exist

### ISSUE THREAD

**Issue by Nitzbon** [BerlusGmbH/Berlussimo#37]
Kaution buchen weiterhin nicht möglich - wahrscheinlich wegen den Feldbezeichnungen.
![table berlussimo kautions_buchungen doesn t exist](https://cloud.githubusercontent.com/assets/17554642/14883598/4da70e82-0d3f-11e6-815c-63b684a8ddc4.jpg)

**Comment by mueller-berlus** [comment]
Wie ich mit meiner Antwort auf #33 bereits zu sagen versuchte, diese Funktionalität sollte so nicht mehr über das Menu zu erreichen sein und kann nicht funktionieren. Ich bin derzeit auf der Suche nach solchen "Blindgängern" und werde sie entfernen.
