### ISSUE TITLE
Login nach frischer Installation klappt nicht

### ISSUE THREAD

**Issue by FreifunkErzgebirge** [BerlusGmbH/Berlussimo#50]
Berlussimo wurde frisch auf Debian 9.1 mit nginx installiert.
Ein Login mit "admin@berlussimo" - "password" klappt nicht.

Im nginx log habe ich folgendes gefunden:
`192.168.3.20 - - [01/Mar/2018:11:24:00 +0100] "POST /login HTTP/1.1" 500 20794 "http://192.168.3.6/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"`

Leider kann ich mir aus HTTP/500 - Internal Server Error nicht viel nehmen.
Die Passwort vergessen Funktion bringt mir nur eine leere Seite (mit Logo und Design, nur ohne Inhalt).

**Comment by mueller-berlus** [comment]
Welchen branch haben Sie installiert?
Wenn man bei Laravel den Debug-Modus aktiviert (config/app.php), bekommt man einen Stacktrace auf der Fehlerseite.

**Comment by FreifunkErzgebirge** [comment]
Installiert ist der develop branch.
Leider kommt erst gar keine Fehlerseite. Ich sehe nur im nginx access-log, dass etwas nicht klappt.
Die Login-Seite bleibt einfach unverändert.
Legt Laravel evtl. noch irgendwo logs ab, wo man genauer auf Fehlersuche gehen kann?

**Comment by FreifunkErzgebirge** [comment]
Gerade hab ich den master branch installiert - dort genau das gleiche Problem.

**Comment by mueller-berlus** [comment]
Wenn der Debug-Modus aktiviert ist, sollte die Antwort einen Trace enthalten. Entweder als HTML-Seite oder als JSON-Objekt.
Unter Chrome kann man sich mit den Entwicklertools die Antworten auf alle Anfragen ansehen. Firefox wird Ähnliches anbieten.
Unter `storage/logs/laravel.log` legt Laravel Informationen ab. Welche dort landen, habe ich noch nicht nachvollzogen.

**Comment by FreifunkErzgebirge** [comment]
Danke, das hat mir sehr weiter geholfen.
Der Fehler lag bei mir, nich an berlussimo - es gab nur ein kleines Problem mit dem MySQL-Server.

**Comment by onlinepilot** [comment]
> Danke, das hat mir sehr weiter geholfen.
> Der Fehler lag bei mir, nich an berlussimo - es gab nur ein kleines Problem mit dem MySQL-Server.

Ich kann mich ebenso nach einer neuen Installation nicht einloggen. Kannst Du Deine Erfahrungen dazu bitte nochmal teilen?

Danke!

**Comment by AlbertEnder** [comment]
Guten Tag
Ich bin ein Fan von Berlussimo und habe es vor Jahren installiert und dann aber wegen diverser Probleme nicht weiter verfolgt. Leider  habe ich weder die Erfahrung, noch die Zeit, um die Applikation wieder zu installieren und zum Laufen zu bringen. Wenn jemand das für mich gegen Bezahlung tun möchte, wäre ich sehr dankbar.
Herzliche Grüsse

**Comment by AlbertEnder** [comment]
Tja, anscheinend ist niemand wirklich interessiert.
Schade.

**Comment by vinnipu** [comment]
Hallo, ich habe das selbe Problem. Was war der Fehler bei MySQL?
