### ISSUE TITLE
Add missing table KAUTION_DATEN to the db schema creation

### ISSUE THREAD

**Issue by powervault76** [BerlusGmbH/Berlussimo#51]
The table `KAUTION_DATEN` is referenced in `legacy/classes/class_kautionen.php` but this table is not created by the db schema creation instructions in `install/DB-Version-0.4.0/`

**Comment by mueller-berlus** [comment]
You are correct. Thanks for the hint. I have created a laravel migration for all legacy tables including KAUTION_DATEN. Unfortunately it might be a while until this change hits the develop tree. So for the time being here is the definition I am going to use:

`CREATE TABLE IF NOT EXISTS `KAUTION_DATEN` (
  `DAT` int(7) NOT NULL AUTO_INCREMENT,
  `MV_ID` int(7) NOT NULL,
  `FELD` varchar(50) NOT NULL,
  `WERT` varchar(100) NOT NULL,
  `AKTUELL` enum('0','1') NOT NULL,
  PRIMARY KEY (`DAT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`

As you can see I switched the engine and the collation. I will close this for now, as a fix is on its way. Although slowly. Feel free to reopen this issue, if necessary.
