### ISSUE TITLE
Passwort setzen für neue Personen ist nicht möglich !

### ISSUE THREAD

**Issue by cst-24** [BerlusGmbH/Berlussimo#53]
Nach der erfolgreichen Installation, ist es nur möglich bei den bestehenden Accounts das Passwort zu setzen.

Wird eine neue Person angelegt, kommt es beim Passwort setzen zum Fehler: 

"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'credentials_api_token_unique' (SQL: insert into `credentials` (`password`, `id`, `updated_at`, `created_at`) values ($2y$10$KIBouA3AsyfQZqN3ZuWHpOdNwsj1JT0KdSgJORJoY97eKTIECe2MS, 1, 2018-07-25 06:41:39, 2018-07-25 06:41:39))"

über  PHPMyAdmin  sieht man das schon bei der 2 ID schon  kein api_token gesetzt wurde. ( siehe Screenshot ) 

![phpmyadmin](https://user-images.githubusercontent.com/41667457/43185834-8f8e4244-8fdc-11e8-8f91-4f5020ff79b1.JPG)

Vorübergehende Lösung:

ich habe die Indizes für die Spalte api_token gelöscht somit ist es möglich erneut User Passwörter anzulegen. 

Woran kann das liegen wie kann man das Problem Lösen ?

**Comment by mueller-berlus** [comment]
Hallo cst-24,

vielen Dank für den Hinweis. Ich habe den Fehler gefunden und entfernt. Der Fix ist im develop branch.

Grüße
Cristian
