### ISSUE TITLE
Installation möglich mit Apache2 statt nginx?

### ISSUE THREAD

**Issue by BlackQube** [BerlusGmbH/Berlussimo#55]
Ist es möglich Berlussimo auch auf Basis des Indianers aufzubauen?

**Comment by mueller-berlus** [comment]
Ja, denke ich schon. Man wird derzeit jedoch zusätzlich ein nginx aufsetzen müssen, da dieser den websocket bereitstellt (https://nchan.io/).
Ich habe vor diese Abhängigkeit auszutauschen, aber das kann noch dauern.

**Comment by BlackQube** [comment]
alles klar, dann muss man als apache nutzer sich einfach mal mit nginx auseinander setzten.

ich schließe das issue.
