### ISSUE TITLE
Installationsanleitung

### ISSUE THREAD

**Issue by aplein** [BerlusGmbH/Berlussimo#58]
Hallo Herr Wehrheim,

ich habe alle Dateien aus dem Download auf unseren Server geladen.
Wie genau Installiere ich das ganze jetzt?
Gibt es hier evtl eine Installationsanleitung?

Herzlichen Dank.
Alfred

**Comment by mueller-berlus** [comment]
Hallo Herr Plein,

Sie können eine rudimentäre Installationsanleitung unter `install/install_instructions.txt` finden. Diese Anleitung richtet sich an erfahrene Benutzer/Entwickler. Wir haben derzeit leider kein entanwenderfreundlicheres Angebot.

Beste Grüße
Cristian
