### ISSUE TITLE
Neuanlage v. Haus oder Objekt nicht möglich

### ISSUE THREAD

**Issue by connectnet** [BerlusGmbH/Berlussimo#62]
``SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'EIGENTUEMER_PARTNER' cannot be null (SQL: insert into `OBJEKT` (`OBJEKT_KURZNAME`, `EIGENTUEMER_PARTNER`, `OBJEKT_AKTUELL`, `OBJEKT_ID`) values (gjhgjhgj, , 1, 1))``

``SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'OBJEKT_ID' cannot be null (SQL: insert into `HAUS` (`HAUS_STRASSE`, `HAUS_NUMMER`, `HAUS_STADT`, `HAUS_PLZ`, `OBJEKT_ID`, `HAUS_AKTUELL`, `HAUS_ID`) values (test, 1, test, 123456, , 1, 1))``

Gibt es ein Manual zur Software?

**Comment by mueller-berlus** [comment]
> Gibt es ein Manual zur Software?

Nein, leider nicht. Das Projekt richtet sich derzeit noch an Entwickler, weil es z.B. noch keine Anleitung gibt. Auch sonst ist Berlussimo noch recht sparsam mit Rückmeldungen, was die Verwendung für neue Benutzer erschwert.

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'EIGENTUEMER_PARTNER' cannot be null
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'OBJEKT_ID' cannot be null

Kein Objekt ohne Partner (Eigentümer). Kein Haus ohne Objekt. Keine Einheit ohne Haus.
