### ISSUE TITLE
Problem bei composer install

### ISSUE THREAD

**Issue by jonas154** [BerlusGmbH/Berlussimo#63]
Ich komme bei der folgenden Zeile nicht weiter: 

`composer install
`
Folgenden Output erhalte ich:

```
root@serve_dev:/var/www/berlussimo# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan ide-helper:generate
Exception: Class debugbar does not exist
Skipping \Barryvdh\Debugbar\Facade.
Exception: Class debugbar does not exist
Skipping \Barryvdh\Debugbar\Facade.
A new helper file was written to _ide_helper.php
Tag Exists: @mixin \Illuminate\Database\Eloquent\Builder in Illuminate\Database\Eloquent\Model
Tag Exists: @mixin \Illuminate\Database\Query\Builder in Illuminate\Database\Eloquent\Model
Tag Exists: @mixin \Eloquent in Illuminate\Database\Eloquent\Model
> php artisan view:clear
Compiled views cleared!
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

Über einen kleinen Tipp würde ich mich sehr freuen!
Beste Grüße!

**Comment by mueller-berlus** [comment]
> Nothing to install or update

Es scheint der Schritt ist bereits abgeschlossen. Ich sehe nichts, das auf einen Fehler hinweist. Was lässt Sie nicht weiter kommen?

**Comment by jonas154** [comment]
Ich habe heute noch einmal eine saubere Installation gemacht und ich konnte mich wieder nicht einloggen (ähnlicher Fall wie bei https://github.com/BerlusGmbH/Berlussimo/issues/61). Es schien ein Problem mit dem PHP auth_socket plugin für die Mysql Datenbank gewesen zu sein. Nach dem Befolgen dieses Tipps https://askubuntu.com/questions/1029177/error-1698-28000-access-denied-for-user-rootlocalhost-at-ubuntu-18-04  klappt nun alles
