### ISSUE TITLE
 Fehler beim Erstellen des Objektes. Code: 500 Message: Internal Server Error

### ISSUE THREAD

**Issue by omaemaru** [BerlusGmbH/Berlussimo#64]
Fehler beim Erstellen des Objektes. Code: 500 Message: Internal Server Error

I get this error whenever I try to create something, any ideas?

**Comment by omaemaru** [comment]
Found the issue.

**Comment by BLAUSICHT** [comment]
What was the Problem? I have the Same issue.

**Comment by Exxinus** [comment]
und was war das Problem? Ich kriege leider auch immer die Fehlermeldung.
