### ISSUE TITLE
Gibt ein  Anleitung um der Programm zu personaliesieren

### ISSUE THREAD

**Issue by bikemopel** [BerlusGmbH/Berlussimo#65]

**Comment by mueller-berlus** [comment]
Derzeit gibt es keine einfache Möglichkeit das Aussehen der Software zu beeinflussen. Dementsprechend ist auch keine Anleitung dafür vorhanden.
Sollte sich an der Situation etwas ändern, so werden die Möglichkeiten in der (nicht vorhandenen) Anleitung #66 beschrieben werden.
Ich werde das Ticket vorerst schließen.
