### ISSUE TITLE
Gibt es irgendwo eine Anleitung wie man mit Programm starten kann?

### ISSUE THREAD

**Issue by bikemopel** [BerlusGmbH/Berlussimo#66]

**Comment by bikemopel** [comment]
Mir gefällt das Programm auf den ersten Blick sehr gut aber es sollte so was wie ein Handbuch geben wie man mit dem Programm auch für seine eigen Firma Arbeiten kann Danke

**Comment by mueller-berlus** [comment]
Ja, so sehen wir das auch.
Der derzeitige Stand der Software lässt noch keinen zuverlässigen Einsatz außerhalb unseres Unternehmens zu. Daher richtet sich das Projekt zur Zeit eher an Entwickler, die bereit sind mit uns Berlussimo neu zu gestallten.
Wenn die Software einen stabilen Zustand erreicht hat, wird es auch eine Anleitung geben.
Ich werde dieses Ticket schließen. Wenn Sie noch Fragen haben, zögern Sie nicht es erneut zu öffnen.
