### ISSUE TITLE
[solved]pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by chrzimmer** [BerlusGmbH/Berlussimo#70]
Hallo zusammen, 

leider schlägt bei mir die Installtion fehl. Ich habe starkes Interesse an einem produktiven Einsatz - komme so aber nicht weiter.
Der Kontext des Fehlers:
"> optipng-bin@3.1.4 postinstall /var/www/berlussimo/node_modules/optipng-bin
> node lib/install.js

  ? optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /var/www/berlussimo/node_modules/pngquant-bin
> node lib/install.js

  ? The `/var/www/berlussimo/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ? pngquant pre-build test failed
  ? compiling from source
  ? pngquant pre-build test passed successfully
  ? Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/var/www/berlussimo/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-26T11_21_46_065Z-debug.log
root@immo-manage:/var/www/berlussimo# npm run prod
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/"

Den Pfad /var/www/berlussimo/node_modules/pngquant-bin gibt es bei mir gar nicht :-(

Kann mir wer helfen das zum Fliegen zu bringen ?

Vielen Dank und viele Grüße
Chris

**Comment by chrzimmer** [comment]
ach so, vielleicht noch ein paar Details :-)
Virtuelle Maschine auf VMware ESXi 6.5
Ubuntu 19.04 Server; php 7.2; remote mysql 5.7.28

Ansonsten wie in install_instructions.txt beschrieben ...

**Comment by chrzimmer** [comment]
habs selber gefunden ... der fehler passiert schon vorher beim Download der libpng12. Ich hab einfach die fürs Ubuntu richtige libpng12 runtergeladen und installiert. 

Ergo: die Zeilen in der install_instructions.txt ist OS-abhängig (vielen vielleicht klar - mir wars nicht)
wget http://ftp.de.debian.org/debian/pool/main/libp/libpng/libpng12-0_1.2.50-2+deb8u3_amd64.deb -P ~
apt install ~/libpng12-0_1.2.50-2+deb8u3_amd64.deb

**Comment by mueller-berlus** [comment]
Ich freue mich, dass Sie selbst eine Lösung gefunden haben. Ich werde dieses Issue also schließen
