### ISSUE TITLE
Wie kann ich die Login-Seite aufrufen

### ISSUE THREAD

**Issue by Mechtilde** [BerlusGmbH/Berlussimo#74]
Hallo,

Ich habe das Programm unter Debian 10 installiert. Hier die wesentlichen Komponenten:

PHP 7.3
MariaDB 10.3
libpng12
nginx 1.14.2

Der Webserver nginx läuft auch und liefert eine Testseite, die in berlussimo/public/ liegt aus. Die dort ebenfalls liegende index.php ergibt "502 - Bad Gateway"

Wer kann mir einen Hinweis geben, dass ich auch eine Login-Maske bekomme?

Viele Grüße

**Comment by Mechtilde** [comment]
Nun erhalte ich die Login-Seite. In der Datei install/config/nginx/default war noch ein php7.0-fpm versteckt.

Der Login funktioniert aber leider nicht.

**Comment by Mechtilde** [comment]
Ich habe schon die Beschreibung von #61 durchgearbeitet und bekomme immer noch den Fehlercode 500. Der Debugger von Firefox gibt einen Hinweis auf die vendor.js.

Weitere Tests und Studium der Logs haben ergeben, dass das Absenden der Login-Daten keinen Zugriff auf die Datenbank auslöst. 

Die in config/database.php eingetragenen Login-Daten werden von php artisan erfolgreich genutzt.

**Comment by Mechtilde** [comment]
Status-Bericht:

Ich konnte Berlussimo erfolgreich auf einer virtuellen Maschine mit Debian 9 (Stretch) installieren. Dort funktioniert auch der Login. Ich kann aber noch kein Haus anlegen. Es kommt die Meldung: Fehler beim Erstellen des Hauses. Code: 500 Message Internal Server Error

**Comment by Mechtilde** [comment]
Für mich erstmal gelöst:
Ich habe einen älteren Rechner mit Debian Stretch als Server aufgesetzt. Das funktioniert.

Es wäre schön, wenn berlussimo in absehbarer Zeit auch auf Debian 10 (Buster) läuft. Das aber nicht erst, wenn in Debian schon die Version 11 (Bullseye) released wird.

**Comment by benitofischer** [comment]
> Für mich erstmal gelöst:
> Ich habe einen älteren Rechner mit Debian Stretch als Server aufgesetzt. Das funktioniert.
...

Wow! Glückwunsch! 
Hab's nun schon mit der 3. VM (u.a. Debian 9.3) versucht. 
In der Original-Anleitung funktionierte so viel nicht, daß ich sie dann angepasst habe und mich Schritt für Schritt immer einen punkt weiter durchgehangelt habe. 
Im Ergebnis aber immer ohne Erfolg. 
Hat das mit der Installation ( https://github.com/Igel18/BerlussimoSetup ) genau so funktioniert?
Oder waren da auch noch Veränderungen duchzuführen?
Ich hab leider neuerdings auch noch das Problem, daß ich auf von meinem Windows 7 mit MobaXterm auf den Server zugreifen kann, aber nicht vom Browser aus. Da werde ich automatisch auf ne "IIS7"-Seite umgeleitet und lande dann bei mickrich-doof. 
Hab dann (nach ca. 2 Wochen durchzechten Nächten und noch mehr grauen Haaren als vorher) das Projekt erstmal nach hinten gestellt.
Frage:
Geht das mit dem alten Rechner besser als in der VM?  
Was hast du anders gemacht, als die Installations-Anleitung hergibt?
Und am Wichtigsten:
Wie hast du es geschafft?

**Comment by Mechtilde** [comment]
Hallo

Am 16.02.20 um 12:27 schrieb benitofischer:
>> Für mich erstmal gelöst:
>> Ich habe einen älteren Rechner mit Debian Stretch als Server aufgesetzt. Das funktioniert.
> ...
> 
> Wow! Glückwunsch! 
> Hab's nun schon mit der 3. VM (u.a. Debian 9.3) versucht. 

Ok. Dann ein bisschen genauer, aber alles ohne jede Garantie:

Zunächst habe ich eine VM (virtualbox) mit Debian 9.12 aufgesetzt
(XFCE-Image)
> In der Original-Anleitung funktionierte so viel nicht, daß ich sie dann angepasst habe und mich Schritt für Schritt immer einen punkt weiter durchgehangelt habe. 

Dann genau nach Anleitung. Ich habe peinlich darauf geachtet, dass
wirklich nodejs_8.x installiert wurde und php7.0.
> Im Ergebnis aber immer ohne Erfolg. 
> Hat das mit der Installation ( https://github.com/Igel18/BerlussimoSetup ) genau so funktioniert?
> Oder waren da auch noch Veränderungen duchzuführen?

Ich habe dem Root des MariaDB-Server *kein* Passwort zugewiesen. Dafür
dann alles als root gemacht und nicht mit sudo
> Ich hab leider neuerdings auch noch das Problem, daß ich auf von meinem Windows 7 mit MobaXterm auf den Server zugreifen kann, aber nicht vom Browser aus. Da werde ich automatisch auf ne "IIS7"-Seite umgeleitet und lande dann bei mickrich-doof.

Bei mir läuft der nginx server auf Port 80 (Standard-Installation bei
Debian). Wie das in einem Windows-Client läuft, weiß ich nicht.

> Hab dann (nach ca. 2 Wochen durchzechten Nächten und noch mehr grauen Haaren als vorher) das Projekt erstmal nach hinten gestellt.
> Frage:
> Geht das mit dem alten Rechner besser als in der VM? 
Ich danach das Verzeichnis "/var/www/berlussimo aus der funktionierenden
VM in das entsprechende Verzeichnis auf der Maschine mit ebenfalls
Debian 9 kopiert.

> Was hast du anders gemacht, als die Installations-Anleitung hergibt?
> Und am Wichtigsten:
> Wie hast du es geschafft? 

Hast du auch /etc/nginx/sites-available/default wie in Zeile 100 f.
editiert?
> 

Viele Grüße

-- 
Mechtilde Stehmann

## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by benitofischer** [comment]
@Mechtilde Danke für die ausführliche Anleitung! 
Bin leider z.Zt. arbeitstechnisch im Stress. Sobald ich zeit finde, werde ich deine Anleitung nochmal genauestens durchgehen und das ganze nochmal von vorne aufsetzen. 
Ich melde mich, sobald ich an dem letzen Punkt angekommen bin. 
Zu deiner Frage:  Bis zum Punkt /etc/nginx/sites-available/default bin ich noch gar nicht gekommen.  Bei mir war bei "# install libpng12"  Schluss mit der Installation.

Viele Grüße zurück .

Und danke nochmal für die Hilfe!

**Comment by Exxinus** [comment]
> Hast du auch /etc/nginx/sites-available/default wie in Zeile 100 f. editiert?

und genau da hänge ich fest. Einfach die beiden Zeilen

# edit default (/etc/nginx/sites-available/default) site to
# reflect settings from install/config/nginx/default

in die /etc/nginx/sites-available/default rein kopieren?
