### ISSUE TITLE
LogIn not possible

### ISSUE THREAD

**Issue by TheAkki** [BerlusGmbH/Berlussimo#77]
I'm nearly happy. After some tries i have a version running with kubuntu 20.04.
I will send a commit next time.

Now, i want to log in with given user name and password. But nothing happen. How can i check what's going wrong.
I had tried:
- Log in with created user in mysql: works
- Show nginx error and access
- show mysql error

Press on "Reset password": a empty gray page is opening.

Some ideas?
Thx.

**Comment by TheAkki** [comment]
I have found in the laravel log 
`[2020-07-28 23:51:28] production.ERROR: PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/berlussimo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/berlussimo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct()
...`
After searching i had found, that is neccessary to adjust the file config/database.php. You can not use local host. You had to use 127.0.0.1
`'host' => env('DB_HOST', '127.0.0.1'),`

The next state state is:
`[2020-07-29 19:10:41] production.ERROR: ErrorException: compact(): Undefined variable: operator in /var/www/berlussimo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1229
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/berlussimo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1229): compact()`
It looks like a problem in laravel.

**Comment by lfirewall1243** [comment]
Have you solved the problem. 

I got the same issue.


By the way; Where is the Laravel Log located? :)

**Comment by lfirewall1243** [comment]
Try this one with an fresh Debian install

https://github.com/benitofischer/BerlussimoSetup

**Comment by TheAkki** [comment]
Thank you.
But i didn't solve the problem.

Unfortunally i can not download debian 9. (Ok, i did not tried the network installer) Normally i make experiments like this in hotels on business trips. Often the internet is not so good. So i try to download the images before at home.
Can i install debian 9 with netinstaller?

I think i had to adjust the composer.json file and change the laravel-framework to 6.0 and laravel-passport to 3.0.
But when i do an update and it goes wrong a second try is often not possible, because i am blocked by github. :(

Maybe next try it works.

**Comment by TheAkki** [comment]
I have found an debian 9 image. Running the skript and reading correctly - It works.
Thank you!

**Comment by benitofischer** [comment]
@lucas12433 Does it really work? I've tried it multiple times; but didn't get it to run properly. :-/

**Comment by TheAkki** [comment]
@benitofischer: Ich habe es mit der o.g. Anleitung in einer VM gemacht.
Debian image und dann alles Schritt für Schritt. Ich versuche damit mal wieder meine Dockerkenntnisse auf zu frischen und ein Docker-Compose zu schreiben. Mal schauen...

**Comment by AlbertEnder** [comment]
Super. Gratuliere. Klingt ja vielversprechend und gibt wieder etwas Hoffnung (endlich)

⁣BlueMail for Android herunterladen ​
